### ISSUE TITLE
How to implement a time lock with seconds as the unit of measurement?

### ISSUE THREAD

**Issue by ZhichunLu-11** [t-bast/lightning-docs#10]
I read the [Spamming the Lightning Network](https://github.com/t-bast/lightning-docs/blob/master/spam-prevention.md) and it's very well written, thanks for the summary!

But I have some confusions about the section on [Bidirectional upfront payment](https://github.com/t-bast/lightning-docs/blob/master/spam-prevention.md#bidirectional-upfront-payment). The design mentions that the time lock for Reverse upfront payment is in seconds (90 seconds, for example). This doesn't seem to be directly implementable in the blockchain script?

The implementation I have in mind is something like this: the time lock between A and B expires and A asks B to make a payment. If B chooses to refuse, A can't enforce it. But maybe A would deduct B's reputation or just choose to close the channel due to B's dishonest behaviour.

I'm curious if this is an accurate description, or is there a better implementation currently available?

Thank you!

**Comment by t-bast** [comment]
It's indeed not enforceable, it's a soft timeout.
If your peer doesn't respect that timeout and you suspect he's trying to cheat, just close the channel and ban him.

**Comment by ZhichunLu-11** [comment]
> It's indeed not enforceable, it's a soft timeout.
> If your peer doesn't respect that timeout and you suspect he's trying to cheat, just close the channel and ban him.

Thank you!
